
server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/${SCHEMA}
    username: ${USERNAME}
    password: ${PASSWORD}
    generate-unique-name: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

